version: 2
jobs:
  test-all-project:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  deploy_to_firebase:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: npx firebase-tools deploy --token $FIREBASE_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-all-project
      - deploy_to_firebase:
          context: firebase-work
          requires:
            - test-all-project